version: "3.7"

services: 
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "4500:80"
    volumes:
      - ./www:/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'

  phpadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports: 
      - "8088:80" # sulla porta 8088 giro la sua porta 80

  backend:
    image: node:latest
    

